### PR TITLE
Can not show when using Get.context with Getx package

### PR DESCRIPTION
**Pull request by TOMSLAUS**
#96

### CODE REVIEW

**Comment by ryanscott0515** [comment]
I noticed this fix didn't re-add the line for adding the overlay to the overlayManager, which is used when checking things like the position of a stacked notification. I made a [PR that adds this back in](https://github.com/TOMSLAUS/Elegant-Notification/pull/1). 

Do you think this could merge into dev instead of the v2.2.1 branch?

**Comment by TOMSLAUS** [comment]
Youre right, didnt notice that.

**Comment by koukibadr** [comment]
@TOMSLAUS thanks for the updates it's a good fix, just update the target branch to dev and not v2.2.1 because we should publish this fix on the next version

**Comment by TOMSLAUS** [comment]
@koukibadr  Thank you, i opened another pull request for dev branch. 
https://github.com/koukibadr/Elegant-Notification/pull/139

**Pull request closed without merging**
